title: "Aineopintojen harjoitustyö: Tietorakenteet ja algoritmit - 2019 p1"
entitle: "Data Structures Project, 2019 p1"
email: ''
description: "Helsingin yliopiston Aineopintojen harjoitustyö: Tietorakenteet ja algoritmit - kurssin kurssisivu"
endescription: "Course page for the Data Structures Project course at the University of Helsinki"
baseurl: '/2019_p1' # the subpath of your site, e.g. /blog
url: https://saskeli.github.io/2019_p1 # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true
